---
engines:
 rubocop:
   enabled: true
   exclude_paths:
     - '**.sql'
     - 'src/test/**'
     - '.mvn/**'
 duplication:
   enabled: true
   exclude_paths:
     - '**.sql'
     - 'src/test/**'
     - '.mvn/**'
 metric:
   enabled: true
   exclude_paths:
     - '**.sql'
     - 'src/test/**'
     - '.mvn/**'
 coverage:
   enabled: true
   exclude_paths:
     - '**.sql'
     - 'src/test/**'
     - '.mvn/**'
languages:
  css:
    extensions:
      - '-css.resource'
exclude_paths:
  - '**.sql'
  - 'src/test/**'
  - '.mvn/**'